### ISSUE TITLE
Meetup and YouTube

### ISSUE THREAD

**Issue by SethGrimes** [ivan-bilan/The-NLP-Pandect#2]
Nice work!

Would you please add to meetups:
- NY-NLP (New York), https://www.meetup.com/NY-NLP/
- DC-NLP (Washington DC), https://www.meetup.com/DC-NLP/
- Philadelphia NLP, https://www.meetup.com/PHL-NLP/

To YouTube channels:
- NLPxing, https://www.youtube.com/channel/UCuGC1JusVvbOGa__qMtH3QA/videos

To newsletters:
- This Week in NLP by Robert Dale, https://www.language-technology.com/twin

**Comment by ivan-bilan** [comment]
Thank you @SethGrimes. These are great suggestions. I've added all of them to the repository.
