### ISSUE TITLE
Add table of content

### ISSUE THREAD

**Issue by shaido987** [ivan-bilan/The-NLP-Pandect#6]
Hello,

Thanks for a great resource.  
It would be good to be able to get a quick overview of what is included here, so my suggestion is to add a table of content with all all section names at the top of the list. Preferably this would have clickable links to go to the section of interest as well.

**Comment by ivan-bilan** [comment]
Great idea, I will look into a way to add this in an intuitive manner.

**Comment by ivan-bilan** [comment]
Just added it, will improve it over time.
